(()=>{'use strict';
const id=new URLSearchParams(location.search).get('doc');
const titles={'msds-education-result':'물질안전보건자료(MSDS) 교육 결과보고서','hot-work-permit':'화기 작업허가서','trestle-permit':'말비계 작업허가서','height-work-permit':'고소작업 허가서'};
if(!titles[id]){document.querySelector('#form').textContent='서류를 선택해 주세요.';return;}
const key='SafetyV27:Form06:'+id,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let draft={};try{draft=JSON.parse(localStorage.getItem(key)||'{}')}catch{};let photos=draft.photos||{};
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function field(k,label,type='text',def=''){const val=k in draft?draft[k]:def;const attrs=`data-key="${k}" aria-label="${esc(label)}"`;return (type==='textarea'?`<textarea ${attrs} rows="2">${esc(val)}</textarea>`:`<input ${attrs} type="${type}" value="${esc(val)}" ${k==='site'?'list="sites" required':''} ${['writer','teacher'].includes(k)?'list="people"':''} ${type==='number'?'min="0"':''}>`)+`<span class="print-value"></span>`;}
const pair=(rows)=>`<table class="pair">${rows.map(r=>`<tr>${r.map(([k,l,t,v])=>`<th>${l}</th><td>${field(k,l,t,v)}</td>`).join('')}</tr>`).join('')}</table>`;
const area=(k,label,def='')=>`<h2>${label}</h2><table><tr><td>${field(k,label,'textarea',def)}</td></tr></table>`;
const sign=k=>`<div class="signcell">${field(k,k==='teacher'?'교육담당자':k)}<small>(서명)</small></div>`;
const approval=()=>`<h2>검토 · 협의 · 승인</h2><table class="sign-table"><tr><th>검토자 · 관리감독자</th><th>협의자 · 안전관리자</th><th>승인자 · 공사책임자</th></tr><tr>${['reviewer','safetyOfficer','approver'].map(k=>`<td>${sign(k)}</td>`).join('')}</tr></table>`;
const choice=(k)=>`<select data-key="${k}" aria-label="점검 ${k}">${['','적합','미흡','해당없음'].map(v=>`<option ${draft[k]===v?'selected':''}>${v}</option>`).join('')}</select><span class="print-value"></span>`;
function checklist(items){return `<table class="checks"><colgroup><col><col style="width:78px"></colgroup><tr><th>작업 전 점검사항</th><th>확인 결과</th></tr>${items.map((x,i)=>`<tr><td>${i+1}. ${x}</td><td class="result">${choice('check_'+i)}</td></tr>`).join('')}</table>`;}
function matrix(headers,rows,prefix){return `<table><thead><tr><th style="width:45px">구분</th>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr><th>${r}</th>${headers.map((h,j)=>`<td>${field(prefix+'_'+i+'_'+j,r+' '+h)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
const safetyFooter='<div class="footer"><span>현장 보관용 · 서명은 출력 후 작성</span><strong>SAFETY FIRST · EVERY DAY</strong></div>';
let body='';
if(id==='msds-education-result'){
 body=pair([[['site','현장명'],['writeDate','작성일','date',today()]],[['siteManager','현장 담당자'],['client','발주처']],[['projectStart','공사 시작일','date'],['projectEnd','공사 종료일','date']],[['projectAmount','공사금액 (원)'],['eduName','교육명','text','물질안전보건자료(MSDS) 교육']],[['eduDate','교육 시작일','date',today()],['eduEndDate','교육 종료일','date',today()]],[['eduHours','교육시간 (시간)','number'],['place','교육장소']],[['teacher','교육담당자'],['target','교육대상','text','현장 근로자']],[['count','교육인원 (명)','number'],['startTime','교육 시작','time']],[['endTime','교육 종료','time'],['resultSummary','교육 결과 요약']]]);
 body+=area('content','교육내용','MSDS의 개요 및 주요내용\n현장 사용 화학제품의 유해·위험성 및 건강 유해성\n취급방법 및 보호구 착용 요령\n저장·보관 방법 및 취급 시 주의사항\n누출·화재 등 비상 시 응급조치 방법\nMSDS 비치 장소 및 경고표지 확인');
 body+='<h2>교육자료 · 사용물질</h2><table><tr><th style="width:30px">번호</th><th>제품명 / 화학물질명</th><th style="width:18%">용도</th><th style="width:23%">제조사</th><th style="width:17%">비고</th></tr>'+Array.from({length:5},(_,i)=>`<tr><td>${i+1}</td>${['product','use','maker','note'].map(k=>`<td>${field('material_'+i+'_'+k,'사용물질 '+(i+1)+' '+k)}</td>`).join('')}</tr>`).join('')+'</table>';
 body+=area('result','교육결과');
 body+='<h2>교육 참석자 · 직접 서명</h2><div class="grid2">'+[0,5].map(start=>'<table class="attendees"><tr><th style="width:27px">번호</th><th>성명</th><th>직종</th><th>서명</th><th>비고</th></tr>'+Array.from({length:5},(_,i)=>{let n=start+i;return `<tr><td>${n+1}</td><td>${field('att_'+n+'_name','참석자 '+(n+1)+' 성명')}</td><td>${field('att_'+n+'_trade','참석자 '+(n+1)+' 직종')}</td><td></td><td>${field('att_'+n+'_note','참석자 '+(n+1)+' 비고')}</td></tr>`}).join('')+'</table>').join('')+'</div>';
 body+='<h2>교육사진</h2><div class="grid2">'+[0,1].map(i=>`<div class="photo" data-photo="${i}"><div class="photo-box">사진 ${i+1}</div><div class="photo-actions"><label>사진 ${i+1} 등록·교체<input type="file" accept="image/*" data-photo-input="${i}"></label><button type="button" data-remove-photo="${i}">삭제</button></div></div>`).join('')+'</div><div class="notes">첨부자료: 교육 참석자 서명 · 교육 실시 사진 · 교육자료(MSDS)</div><table><tr><th style="width:25%">교육담당자 확인</th><td>'+sign('teacherConfirm')+'</td><th style="width:15%">확인일</th><td>'+field('confirmDate','확인일','date')+'</td></tr></table>';
}else{
 body=pair([[['site','현장명'],['permit','허가번호']],[['siteManager','현장 담당자'],['client','발주처']],[['projectStart','공사 시작일','date'],['projectEnd','공사 종료일','date']],[['projectAmount','공사금액 (원)'],['company','업체명']],[['writer','작성자'],['trade','작업공종']],[['place','작업장소'],['writeDate','작성일','date',today()]],[['count','작업인원 (명)','number'],['startDate','허가 시작일','date']],[['endDate','허가 종료일','date'],['startTime','작업 시작','time']],[['endTime','작업 종료','time'],['foreman','작업반장']],[['phone','연락처'],['contextNote','현장정보 확인']]]);
 body+=area('work','주요 작업내용');
 if(id==='hot-work-permit'){
 body+=pair([[['watcher','화재감시자'],['watcherPhone','감시자 연락처']],[['zone','지하층 / 인화물질 5m 이내 여부'],['equipment','지급장비 / 수량']]]);
 body+='<div class="notes">감시자 지급장비: 확성기 · 휴대용 조명기구 · 방연마스크 (각 수량 기재)</div>';
 body+='<div class="grid2"><div>'+area('risk','주요 잠재위험')+'</div><div>'+area('measure','관리대책')+'</div></div>'+area('caution','작업 시 유의사항');
 body+=checklist(['화재감시자 배치 및 감시범위 확인','확성기·휴대용 조명·방연마스크 등 대피장비 확보','인근 인화성 액체 방호·격리 및 원본 현장기준 5m 이상 이격 확인','작업구역에 적정 소화기구 배치','용접불티 비산방지덮개·방화포 설치','인화성 증기·용접 흄 제거를 위한 환기 조치','작업자 화재예방·대피교육 실시','작업에 적합한 개인보호구 착용','용접·용단·가열·연마 기계 및 기구 점검']);
 body+=approval()+'<div class="notes">허가 유효기간: 원본 현장기준 최대 7일. 조건 변경 시 재검토.</div><h2>작업 전 확인</h2>'+matrix(['1일차','2일차','3일차','4일차','5일차','6일차','7일차','비고'],['공사팀','안전팀'],'daily');
 body+='<h2>종결 확인</h2><table><tr>'+['관리감독자','안전관리자','공사책임자'].map((x,i)=>`<td>${x}${sign('close_'+i)}</td>`).join('')+'</tr></table><div class="notes">작업 종료 후 잔불 등 이상 유무 확인 및 종결 처리하여 현장 안전팀에 제출합니다.</div>';
 }else if(id==='trestle-permit'){
 body+=pair([[['equipment','사용장비'],['validity','허가 유효기간 / 조건']]])+area('measure','안전조치사항');
 const items=['알루미늄 말비계 사용 및 임의제작 금지','발판폭 40cm 이상 / 사용높이 120cm 이하 / 길이 2m 이하 (제공 원본 현장기준)','지주와 바닥면 각도 75도 이하','작업방법 및 순서 숙지','작업자 보호구 적정 착용','관리감독자 지휘하에 작업','기타 필요한 안전조치 시행'];
 body+='<h2>말비계작업 주요 점검사항 · 관리감독자 확인</h2><table><colgroup><col style="width:52%">'+Array(5).fill('<col style="width:7%">').join('')+'<col style="width:13%"></colgroup><tr><th>점검항목</th>'+['1주차','2주차','3주차','4주차','5주차','비고'].map(x=>`<th>${x}</th>`).join('')+'</tr>'+items.map((x,i)=>`<tr><td>${i+1}. ${x}</td>${Array.from({length:5},(_,j)=>`<td>${field('week_'+i+'_'+j,(i+1)+'번 '+(j+1)+'주차')}</td>`).join('')}<td>${field('weeknote_'+i,(i+1)+'번 비고')}</td></tr>`).join('')+'</table><div class="notes">주차별 확인 결과를 기재: 적합 / 미흡 / 해당없음. 해당없음 사유는 비고에 기록.</div>';
 body+=approval()+area('reviewWork','검토의견 · 공사')+area('reviewSafety','검토의견 · 안전')+'<div class="notes">발부 절차: 협력업체 작성 → 관리감독자 검토 → 안전팀 검토 → 일일안전회의 공유 → 작업장소 부착.<br>원본 현장기준: 동일 세부공종 최대 30일. 위 수치 및 기간은 제공 양식 기준이며 현장 조건과 장비 기준을 함께 확인합니다.</div>';
 }else{
 body+=pair([[['equipment','사용장비 / 형식'],['height','작업높이 (m)','number']],[['supervisor','작업지휘자 / 신호수'],['emergency','비상연락처 / 구조방법']]]);
 body+='<div class="grid2"><div>'+area('risk','주요 위험요인')+'</div><div>'+area('measure','안전조치 / 작업중지 조건')+'</div></div>';
 body+=checklist(['작업 위치·높이·개구부·지반과 주변 전선 등 위험요인 확인','견고한 작업발판·안전한 승강통로 확보','단부·개구부의 난간·덮개 등 추락방지 조치','안전모·안전화 및 작업에 맞는 안전대 상태·착용 확인','안전대 부착설비·생명줄 및 연결 상태 점검','비계의 고정·전도방지·바퀴 잠금 및 적재하중 확인','고소작업대 검사·운전자 자격·수평·지반·아웃트리거 확인 (해당 시)','비상정지·과상승방지 등 장비 안전장치 점검 (해당 시)','낙하물 방지·하부 출입통제 및 신호체계 확보','강풍·비·결빙·시야불량 시 중지기준 및 제조사 제한 확인','작업자 교육·지휘자 배치 및 비상구조 계획 공유']);
 body+=area('correction','미흡항목 조치 / 해당없음 사유')+approval();
 body+='<div class="notes">미흡항목은 조치·재확인 후 작업합니다. 추락방지 조치 없이 작업하지 않으며, 작업조건 변경·악천후·장비 이상 시 중지하고 재검토합니다. 본 양식은 현장 관리용이며 작업계획서·위험성평가 등 필요한 서류를 대체하지 않습니다.</div><table><tr><th>종료일시</th><td>'+field('closeTime','작업 종료일시','datetime-local')+'</td><th>종료 확인자</th><td>'+sign('closer')+'</td></tr></table>';
 }
}
document.title=titles[id];document.querySelector('#form').innerHTML=`<article class="sheet ${id==='msds-education-result'?'msds':'compact'}"><header><h1>${titles[id]}</h1><p>${id==='msds-education-result'?'교육정보 · 사용물질 · 참석자 · 교육사진':'작업조건 · 안전점검 · 검토 및 승인'}</p></header>${body}${safetyFooter}</article>`;
if(id==='height-work-permit')document.querySelector('#form').insertAdjacentHTML('beforeend','<div class="source">작성 참고: <a target="_blank" rel="noopener" href="https://www.law.go.kr/lsLinkCommonInfo.do?lsJoLnkSeq=1028063341">산업안전보건기준에 관한 규칙 제42~44조</a> · <a target="_blank" rel="noopener" href="https://www.goe.go.kr/resource/old/BBSMSTR_000000030111/BBS_202402060446298010.pdf">경기도교육청 고소작업 점검표</a> · <a target="_blank" rel="noopener" href="https://oshri.kosha.or.kr/kosha/report/notice.do?articleNo=455685&attachNo=262320&mode=download">안전보건공단 고소작업대 자료</a></div>');
const root=document.querySelector('#form');
function mirrors(){root.querySelectorAll('[data-key]').forEach(el=>{const span=el.nextElementSibling;if(span?.classList.contains('print-value'))span.textContent=el.value;if(el.tagName==='TEXTAREA'){el.style.height='auto';el.style.height=Math.max(30,el.scrollHeight)+'px'}})}
function data(){const v={schema:'document-form06',photos};root.querySelectorAll('[data-key]').forEach(el=>v[el.dataset.key]=el.value);return v;}
function persist(){try{localStorage.setItem(key,JSON.stringify(data()));document.querySelector('#notice').textContent='';return true}catch{document.querySelector('#notice').textContent='저장공간이 부족합니다. 사진 수 또는 크기를 줄인 후 다시 저장해 주세요.';return false}}
function showPhotos(){[0,1].forEach(i=>{const box=root.querySelector(`[data-photo="${i}"] .photo-box`);if(!box)return;box.replaceChildren();if(photos[i]){const img=document.createElement('img');img.src=photos[i];img.alt='교육사진 '+(i+1);box.append(img)}else box.textContent='사진 '+(i+1)});}
let pendingImages=0;
root.addEventListener('input',()=>{mirrors();persist();parent.dispatchEvent(new Event('minworks:form-input'))});
root.addEventListener('change',async e=>{const input=e.target;if(!input.matches('[data-photo-input]'))return;const file=input.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){document.querySelector('#notice').textContent='이미지 파일을 선택해 주세요.';return}pendingImages++;try{const bitmap=await createImageBitmap(file);const ratio=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();photos[input.dataset.photoInput]=canvas.toDataURL('image/jpeg',.78);showPhotos();persist();parent.dispatchEvent(new Event('minworks:form-input'))}catch{document.querySelector('#notice').textContent='사진을 읽지 못했습니다. JPG 또는 PNG 파일로 다시 선택해 주세요.'}finally{pendingImages--;input.value=''}});
root.addEventListener('click',e=>{const b=e.target.closest('[data-remove-photo]');if(!b)return;delete photos[b.dataset.removePhoto];showPhotos();persist();parent.dispatchEvent(new Event('minworks:form-input'))});
const context=parent.MIN_WORKS_DOCUMENT_CONTEXT;for(const [listId,values] of [['sites',(context?.sites?.()||[]).map(site=>site.name)],['people',context?.people?.()||(parent.MIN_WORKS_EMPLOYEES||[]).map(p=>[p.name,p.rank].filter(Boolean).join(' '))]]){const list=document.createElement('datalist');list.id=listId;[...new Set(values)].filter(Boolean).forEach(v=>{const opt=document.createElement('option');opt.value=v;list.append(opt)});root.append(list)}
mirrors();showPhotos();
document.querySelector('#previewToggle').addEventListener('click',()=>{const on=document.body.classList.toggle('print-preview');mirrors();document.querySelector('#previewToggle').textContent=on?'작성 화면으로':'출력 미리보기';document.querySelector('#pageHint').textContent=on?'A4 세로 · 여백 10mm · 입력량에 따라 다음 장으로 이어집니다.':'';});
function applyContext(site){if(!site)return;const values={site:site.name,siteManager:site.manager||'',client:site.client||'',projectStart:site.start||'',projectEnd:site.end||'',projectAmount:site.amount||'',company:site.company||'(주)민커뮤니케이션'};Object.entries(values).forEach(([key,value])=>{const el=root.querySelector('[data-key="'+key+'"]');if(el)el.value=value});mirrors();persist()}
root.querySelector('[data-key="site"]')?.addEventListener('change',event=>{const site=(context?.sites?.()||[]).find(item=>item.name===event.target.value);if(site){context.select(site.name);applyContext(site)}});
window.MIN_WORKS_FORM_TOOL={data(){if(pendingImages)throw Error('사진을 처리 중입니다. 잠시 후 저장해 주세요.');if(!persist())throw Error('브라우저 저장공간이 부족합니다.');return data()},validate(){return root.querySelector('[data-key="site"]').reportValidity()},print(){if(pendingImages){document.querySelector('#notice').textContent='사진 처리가 끝난 뒤 인쇄해 주세요.';return}mirrors();window.print()},applyContext};
applyContext(context?.current?.());
window.addEventListener('beforeprint',mirrors);new ResizeObserver(()=>parent.postMessage({type:'minworks:form-height',height:document.body.scrollHeight},location.origin==='null'?'*':location.origin)).observe(document.body);
})();
