/* MIN WORKS v55: TBM authoring, navigation and installation help. */
(() => {
  'use strict';

  const $ = s => document.querySelector(s);
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function init() {
    const nav=$('.mobile-nav');
    const items=[['dashboard','home','홈'],['daily','edit_note','공사일보'],['documents','folder_open','현장서류'],['issues','report_problem','이슈관리']];
    nav.innerHTML=items.map(([view,icon,label])=>`<button type="button" data-view="${view}"><span class="material-symbols-rounded">${icon}</span><b>${label}</b></button>`).join('');
    const sync=()=>nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',$('#'+b.dataset.view+'View')?.classList.contains('active')));
    nav.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{window.showView(b.dataset.view);window.MIN_WORKS_TEST_UNREAD?.clear(b.dataset.view);sync();}));
    document.querySelectorAll('.view').forEach(v=>new MutationObserver(sync).observe(v,{attributes:true,attributeFilter:['class']}));sync();
    const parent=$('.nav-parent[data-view="documents"]');
    const quick=document.createElement('button');quick.type='button';quick.className='tbm-quick';quick.textContent='TBM 작성';quick.setAttribute('aria-label','TBM일지 작성');parent.after(quick);
    const sub=document.createElement('button');sub.type='button';sub.className='nav-subgroup';sub.dataset.docFolder='tbm';sub.innerHTML='<span class="material-symbols-rounded">groups</span><b>TBM 일지</b>';
    $('.nav-submenu').prepend(sub);
    const category=document.createElement('button');category.type='button';category.dataset.docFolder='tbm';category.innerHTML='<span class="material-symbols-rounded">groups</span><div><b>TBM 일지</b><small>작업 전 회의 기록</small></div><i class="material-symbols-rounded" aria-hidden="true">arrow_forward</i>';$('.document-category-grid').prepend(category);
    const panel=document.createElement('section');panel.className='sample-panel tbm-panel';panel.dataset.docPanel='tbm';panel.hidden=true;
    panel.innerHTML='<header><div><small>TOOL BOX MEETING</small><h3>TBM 일지</h3></div><button type="button" class="secondary" id="tbmNew">새 일지 작성</button></header><p>회사 자료 · 저장 완료 후 다른 직원과 공유됩니다.</p><form id="tbmForm"><div class="tbm-fields"><label>현장명<input name="site" list="tbmSites" required maxlength="120" placeholder="현장을 선택하거나 입력하세요"><datalist id="tbmSites"></datalist></label><label>작업일<input name="date" type="date" required></label><label>회의 시간<input name="time" type="time" required></label><label>진행자<input name="leader" required maxlength="80"></label><label class="wide">참석자<textarea name="attendees" required placeholder="참석자 이름을 입력하세요"></textarea></label><label class="wide">주요 작업내용<textarea name="work" required></textarea></label><label class="wide">위험요인<textarea name="risks" required></textarea></label><label class="wide">안전대책 및 전달사항<textarea name="measures" required></textarea></label></div><div class="tbm-actions"><button class="primary" type="submit">TBM 일지 저장</button><span id="tbmSaveState" role="status"></span></div></form><h3>저장된 TBM 일지</h3><div id="tbmRecords"></div>';
    $('#documentsView').append(panel);
    const form=$('#tbmForm'), key='minWorksTbmRecordsV1', draftKey='minWorksTbmDraftV1';let editId=null;
    const read=()=>{const value=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(value))throw Error('invalid');return value;};
    const collect=()=>Object.fromEntries(new FormData(form));
    const fill=data=>{for(const e of form.elements)if(e.name)e.value=data[e.name]||'';};
    const today=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
    const blank=()=>{window.MIN_WORKS_TBM_DIRTY=false;editId=null;fill({date:today(),time:'08:00'});$('#tbmSaveState').textContent='';};blank();
    try{const draft=JSON.parse(localStorage.getItem(draftKey)||'null');if(draft){window.MIN_WORKS_TBM_DIRTY=true;fill(draft.data);editId=draft.id||null;$('#tbmSaveState').textContent='작성 중인 내용 복원';}}catch{$('#tbmSaveState').textContent='임시저장 내용을 불러오지 못했습니다.';}
    form.addEventListener('input',()=>{window.MIN_WORKS_TBM_DIRTY=true;try{localStorage.setItem(draftKey,JSON.stringify({id:editId,data:collect()}));$('#tbmSaveState').textContent='임시저장됨';}catch{$('#tbmSaveState').textContent='저장공간 부족 · 화면을 닫기 전에 내용을 복사해 주세요.';}});
    function render(){try{$('#tbmRecords').replaceChildren();const rows=read().sort((a,b)=>b.date.localeCompare(a.date));if(!rows.length){$('#tbmRecords').textContent='저장된 TBM 일지가 없습니다.';return;}rows.forEach(row=>{const b=document.createElement('button');b.type='button';b.className='tbm-record';b.textContent=`${row.date} · ${row.site} · ${row.work}`;b.addEventListener('click',()=>{fill(row);editId=row.id;$('#tbmSaveState').textContent='수정 후 저장하면 기존 일지가 갱신됩니다.';form.scrollIntoView({block:'start',behavior:'smooth'});});$('#tbmRecords').append(b);});}catch{$('#tbmRecords').textContent='저장 자료를 읽지 못했습니다. 기존 자료는 유지됩니다.';}}
    form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;if(form.dataset.saving)return;form.dataset.saving='1';window.MIN_WORKS_TRANSACTION=true;const old=localStorage.getItem(key);try{if(!window.MIN_WORKS_USER)throw Error('로그인이 필요합니다.');const data=collect();if(Object.values(data).some(v=>!String(v).trim())){$('#tbmSaveState').textContent='빈칸을 입력해 주세요.';return;}const rows=read();const id=editId||(crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2));const existing=rows.find(r=>r.id===id);if(existing&&existing.authorId&&existing.authorId!==(window.MIN_WORKS_USER.id||window.MIN_WORKS_USER.name)&&window.MIN_WORKS_USER.role!=='admin')throw Error('작성자 또는 관리자만 수정할 수 있습니다.');const next={...data,id,authorId:existing?.authorId||(window.MIN_WORKS_USER.id||window.MIN_WORKS_USER.name),author:existing?.author||currentUser,updatedAt:new Date().toISOString()};const i=rows.findIndex(r=>r.id===id);if(i>=0)rows[i]=next;else rows.push(next);localStorage.setItem(key,JSON.stringify(rows));await window.MIN_WORKS_CLOUD.saveNow();window.MIN_WORKS_TBM_DIRTY=false;editId=id;localStorage.removeItem(draftKey);$('#tbmSaveState').textContent='저장 완료';render();}catch(error){if(old===null)localStorage.removeItem(key);else localStorage.setItem(key,old);$('#tbmSaveState').textContent='저장 실패 · 입력 내용을 유지했습니다. '+error.message;}finally{delete form.dataset.saving;window.MIN_WORKS_TRANSACTION=false;}});
    $('#tbmNew').addEventListener('click',()=>{if(localStorage.getItem(draftKey)&&!confirm('작성 중인 임시 내용을 비우고 새 일지를 작성할까요?'))return;localStorage.removeItem(draftKey);blank();form.elements.site.focus();});
    function open(){window.showView('documents');document.querySelectorAll('[data-doc-panel]').forEach(p=>p.hidden=p!==panel);document.querySelectorAll('[data-doc-folder]').forEach(b=>{b.classList.toggle('selected',b.dataset.docFolder==='tbm');b.classList.toggle('active',b.dataset.docFolder==='tbm');});$('.nav-cluster').classList.add('open');parent.setAttribute('aria-expanded','true');$('#tbmSites').innerHTML=[...new Set([...document.querySelectorAll('[data-site-row]')].map(r=>r.dataset.siteRow))].map(s=>`<option value="${esc(s)}">`).join('');render();}
    [quick,sub,category].forEach(b=>b.addEventListener('click',open));render();
    setupInstall();
    const help=document.createElement('article');help.className='help-card static';help.innerHTML='<span class="material-symbols-rounded">groups</span><div><h3>TBM 일지 작성</h3><p>현장서류 옆 TBM 작성 또는 현장서류 → TBM 일지를 누르세요. 현장·작업일·회의 시간·진행자·참석자·작업내용·위험요인·안전대책을 입력하고 저장합니다. 저장된 일지를 누르면 수정할 수 있습니다. 작성 중인 내용은 임시저장됩니다.</p></div>';$('.help-grid').append(help);
  }
  function setupInstall(){
    const box=document.createElement('details');box.className='mw-install-help';box.id='mwInstallHelp';
    box.innerHTML=`<summary><span class="material-symbols-rounded">install_mobile</span><b>민웍스 설치</b><span>기종별 설치 방법 보기</span></summary><div class="install-help-body">
    <p>앱스토어 검색 대신 민웍스 웹사이트를 홈 화면에 추가하세요. 기종보다 사용 중인 브라우저와 운영체제 버전에 따라 메뉴가 달라집니다.</p>
    <details open><summary>먼저 확인 · 카카오톡 등 앱 안에서 열었나요?</summary><ol><li>현재 화면의 더보기(⋮ 또는 …)나 공유 메뉴를 여세요.</li><li>‘외부 브라우저로 열기’, ‘Safari로 열기’ 또는 ‘다른 브라우저로 열기’가 있으면 선택하세요. 메뉴 이름과 위치는 앱마다 다릅니다.</li><li>해당 메뉴가 없으면 주소를 복사하고, 아이폰은 Safari / 갤럭시는 Chrome 또는 삼성 인터넷을 직접 연 뒤 주소창에 붙여넣으세요.</li><li>페이지가 열린 뒤 아래 기종별 순서로 진행하세요.</li></ol></details>
    <details open><summary>아이폰 · Safari</summary><ol><li>Safari에서 민웍스 주소를 엽니다.</li><li>공유 버튼(네모 위 화살표)을 누릅니다. 최신 Safari에서 안 보이면 더보기(…) 안의 공유를 확인하세요.</li><li>메뉴를 아래로 내려 ‘홈 화면에 추가’를 선택합니다. 없으면 ‘동작 편집’에서 추가하세요.</li><li>이름을 MIN WORKS로 확인하고, ‘웹 앱으로 열기’ 옵션이 보이면 켠 뒤 ‘추가’를 누릅니다.</li><li>홈 화면으로 나가 MIN WORKS 아이콘을 눌러 실행합니다.</li></ol><p>구형 iOS에서는 ‘웹 앱으로 열기’ 옵션이 없어도 홈 화면에 추가할 수 있습니다.</p><a href="https://support.apple.com/ko-kr/guide/iphone/iphea86e5236/ios" target="_blank" rel="noopener">Apple 공식 안내</a></details>
    <details><summary>갤럭시 · Chrome (S·A·Z Fold·Z Flip)</summary><ol><li>Chrome에서 민웍스 주소를 엽니다.</li><li>오른쪽 위 더보기(⋮)를 누릅니다.</li><li>‘홈 화면에 추가’ → ‘설치’를 선택합니다. 버전에 따라 ‘앱 설치’로 표시될 수도 있습니다.</li><li>안내 창에서 설치를 완료하고, 홈 화면 또는 앱스 화면의 MIN WORKS 아이콘을 눌러 실행합니다.</li></ol><p>설치 대신 ‘바로가기 만들기’가 나오면 웹사이트 바로가기로 추가할 수 있습니다.</p><a href="https://support.google.com/chrome/answer/9658361?hl=ko&co=GENIE.Platform%3DAndroid" target="_blank" rel="noopener">Google 공식 안내</a></details>
    <details><summary>갤럭시 · 삼성 인터넷</summary><ol><li>삼성 인터넷에서 민웍스 주소를 엽니다.</li><li>오른쪽 아래 메뉴(☰)를 누릅니다.</li><li>‘현재 페이지 추가’ 또는 ‘페이지 추가’를 선택한 뒤 ‘홈 화면’을 누릅니다.</li><li>이름을 확인하고 ‘추가’를 누릅니다. ‘앱 설치’ 또는 ‘앱스 화면’으로 표시되면 해당 안내에 따라 추가하세요.</li><li>홈 화면이나 앱스 화면에서 MIN WORKS를 실행합니다.</li></ol><p>삼성 인터넷 버전과 사이트에 따라 표시되는 항목이 다릅니다. 찾기 어려우면 주소를 Chrome으로 옮겨 위 순서로 진행하세요.</p><a href="https://www.samsung.com/uk/support/mobile-devices/using-the-samsung-internet-app/" target="_blank" rel="noopener">삼성 인터넷 메뉴 안내</a></details>
    <details><summary>설치 메뉴가 안 보이거나 실행이 안 될 때</summary><ul><li>카카오톡 안의 화면이 아닌 Safari·Chrome·삼성 인터넷에서 열었는지 확인하세요.</li><li>브라우저를 업데이트하고 일반 탭에서 다시 시도하세요. 이미 설치했다면 홈 화면과 앱스 화면을 먼저 확인하세요.</li><li>공유받은 민웍스 주소가 맞는지 확인하세요. 테스트판 localhost 주소는 이 PC 전용이며 휴대폰에서 그대로 열 수 없습니다.</li><li>사내 Wi-Fi의 테스트 주소는 PC가 켜져 있고 같은 네트워크에 연결되어야 합니다. HTTP 테스트 주소에서는 앱 설치 대신 바로가기만 제공될 수 있습니다.</li><li>설치 후 같은 직원 계정으로 로그인하세요. 작성 중인 임시저장 내용은 해당 브라우저에만 남으므로 이동 전에 저장을 완료하세요.</li></ul></details></div>`;
    $('.help-grid').before(box);
    const show=()=>{window.showView('help');box.open=true;box.scrollIntoView({behavior:'smooth',block:'start'});};
    document.addEventListener('click',e=>{if(e.target.closest('.install-min-works')){e.preventDefault();e.stopImmediatePropagation();show();}},true);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
