(()=>{'use strict';
const API='https://min-works-api.forjaejun.workers.dev',KEY='minWorksSessionV1',$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view='',checking=false,installer=null,user=null,pending=false;
window.MINWORKS_PLUS_READY=false;
const gate=document.createElement('section');gate.id='plusGate';gate.className='plus-gate';gate.innerHTML='<div class="plus-auth-card"><div class="plus-wordmark">민웍스<span>+</span></div><p class="plus-tagline">현장을 한눈에, 민웍스 플러스</p><div id="plusAuthContent"></div><p id="plusAuthMessage" role="status"></p><button class="plus-install-text" type="button">앱 설치 방법</button></div>';document.body.append(gate);gate.querySelector('.plus-install-text').onclick=install;
function show(){gate.hidden=false;document.querySelector('main').hidden=true;window.MINWORKS_PLUS_READY=false}
function form(mode){pending=false;show();view=mode;const host=$('#plusAuthContent');
 if(mode==='pending'){pending=true;host.innerHTML='<h2>민웍스+ 승인 대기</h2><p>관리자가 직원관리에서 <b>민웍스+ 승인</b>을 누르면 사용할 수 있어요. 민웍스 본판 승인은 필요하지 않아요.</p><button id="plusCheck" class="plus-primary">승인 확인</button><button id="plusBack">다른 계정으로 연결</button>';$('#plusCheck').onclick=check;$('#plusBack').onclick=()=>form('choose');return}
 if(mode==='blocked'){host.innerHTML='<h2>계정 사용 중지</h2><p>관리자에게 이용 권한을 확인해 주세요.</p><button id="plusCheck">다시 확인</button><button id="plusBack">다른 계정으로 연결</button>';$('#plusCheck').onclick=check;$('#plusBack').onclick=()=>form('choose');return}
 if(mode==='choose'){host.innerHTML='<h2>민웍스+ 시작하기</h2><p>본판 설치 없이 민웍스+만 사용할 수 있어요.</p><button class="plus-primary" data-plus-mode="connect">이미 등록한 직원 · 기기 연결</button><button data-plus-mode="register">처음 사용하는 직원 · 등록 신청</button><button class="plus-link" data-plus-mode="admin">관리자 로그인</button><small>브라우저·설치 앱의 저장공간이 다르면 처음 한 번 기기 연결이 필요해요.</small>';host.querySelectorAll('[data-plus-mode]').forEach(b=>b.onclick=()=>form(b.dataset.plusMode));return}
 const departments=['시공팀','설계팀','사인팀','임원','공무팀','관리팀'],ranks=['대표이사','상무이사','실장','부장','차장','과장','대리','주임','사원'];
 host.innerHTML=`<h2>${mode==='connect'?'기존 직원 기기 연결':mode==='register'?'민웍스+ 등록 신청':'관리자 로그인'}</h2><form id="plusLoginForm">${mode==='admin'?'<label>관리자 이메일<input name="email" type="email" autocomplete="username" required></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" required></label>':mode==='connect'?'<p>관리자가 직원관리에서 <b>본인의 기기 연결코드</b>를 발급해 주세요. 기존 직원의 권한으로 연결됩니다.</p><label>8자리 기기 연결코드<input name="code" inputmode="numeric" pattern="[0-9]{8}" maxlength="8" autocomplete="one-time-code" required placeholder="8자리 코드"></label>':`<p>관리자가 발급한 6자리 접속코드를 입력하고 등록하세요.</p><label>접속코드<input name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="one-time-code" required></label><label>이름<input name="name" minlength="2" maxlength="30" autocomplete="name" required></label><label>부서<select name="department" required><option value="">선택</option>${departments.map(x=>`<option>${x}</option>`).join('')}</select></label><label>직급<select name="rank" required><option value="">선택</option>${ranks.map(x=>`<option>${x}</option>`).join('')}</select></label>`}<button class="plus-primary" type="submit">${mode==='register'?'플러스 등록 신청':mode==='admin'?'로그인':'이 기기 연결'}</button></form><button id="plusBack" class="plus-link">뒤로</button>`;
 $('#plusBack').onclick=()=>form('choose');$('#plusLoginForm').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;$('#plusAuthMessage').textContent='';try{const data=Object.fromEntries(new FormData(e.currentTarget));const r=await request(mode==='admin'?'/admin/login':mode==='connect'?'/employee/connect-device':'/plus/register',{method:'POST',body:JSON.stringify(data)},false);if(!r.ok)throw Error(r.error||'등록하지 못했습니다.');localStorage.setItem(KEY,r.token);await check()}catch(error){$('#plusAuthMessage').textContent=error.message}finally{b.disabled=false}};
}
async function request(path,options={},auth=true){const token=localStorage.getItem(KEY);const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(auth&&token?{Authorization:'Bearer '+token}:{})},cache:'no-store'});return r.json()}
async function check(){if(checking)return;checking=true;try{if(!localStorage.getItem(KEY)){if(!view||view==='pending'||view==='blocked')form('choose');return}const r=await request('/plus/session');if(r.ok){user=r.user;window.MINWORKS_PLUS_READY=true;pending=false;view='';gate.hidden=true;document.querySelector('main').hidden=false;$('#plusAuthMessage').textContent='';window.dispatchEvent(new Event('minworks:plus-ready'))}else if(r.loginRequired){localStorage.removeItem(KEY);if(!['register','connect','admin','choose'].includes(view))form('choose')}else if(r.pending){if(view!=='pending')form('pending')}else{if(view!=='blocked')form('blocked')}}catch(error){show();if(!view){$('#plusAuthContent').innerHTML='<h2>연결을 확인해 주세요</h2><button id="plusCheck">다시 연결</button>';$('#plusCheck').onclick=check}$('#plusAuthMessage').textContent='서버에 연결하지 못했어요. 인터넷 연결을 확인해 주세요.'}finally{checking=false}}
window.MINWORKS_PLUS_AUTH={check};
const installDialog=document.createElement('dialog');installDialog.id='plusInstallDialog';installDialog.innerHTML='<header><h2>민웍스+ 설치</h2><button id="closeInstall">닫기 ✕</button></header><section><div class="plus-install-preview"><img src="plus-icon-192.png" alt="민웍스 플러스 앱 아이콘"><div><b>민웍스+</b><p>공사일보를 확인하는 별도 앱</p></div></div><p>민웍스 본판을 설치하지 않아도, 홈 화면에 <b>민웍스+ 아이콘만</b> 추가할 수 있어요.</p><button id="plusNativeInstall" hidden>민웍스+ 앱 설치</button><h3>아이폰 · Safari</h3><p>공유 버튼 → 홈 화면에 추가 → 추가를 누르세요. ‘웹 앱으로 열기’가 표시되면 켜 주세요. 카카오톡 등 앱 안에서 열었다면 Safari에서 다시 열어주세요.</p><h3>갤럭시 · Chrome</h3><p>오른쪽 위 ⋮ → 앱 설치 또는 홈 화면에 추가를 선택하세요.</p><h3>갤럭시 · 삼성 인터넷</h3><p>메뉴 ≡ → 현재 페이지 추가 → 홈 화면을 선택하세요.</p><p>설치한 아이콘으로 열고 등록하세요. 이미 등록했는데 다시 연결 화면이 나오면 관리자가 발급한 본인의 8자리 기기 연결코드로 이어서 사용할 수 있어요.</p></section>';document.body.append(installDialog);$('#closeInstall').onclick=()=>installDialog.close();
async function install(){if(!installDialog.open)installDialog.showModal()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installer=e;$('#plusNativeInstall').hidden=false});$('#plusNativeInstall').onclick=async()=>{if(!installer)return;const p=installer;installer=null;await p.prompt();$('#plusNativeInstall').hidden=true};$('#plusInstall').onclick=install;window.addEventListener('appinstalled',()=>{installer=null;$('#plusNativeInstall').hidden=true});if(location.hash==='#install')install();
$('#plusAccount').onclick=()=>{const d=document.createElement('dialog');d.className='plus-account-dialog';d.innerHTML=`<h2>${esc(user?.role==='admin'?'관리자':[user?.name,user?.rank].filter(Boolean).join(' '))}</h2><p>민웍스 ${user?.mainEnabled?'승인':'미승인'} · 민웍스+ ${user?.plusEnabled?'승인':'미승인'}</p><button id="plusLogout">이 기기 로그아웃</button><button id="plusAccountClose">닫기</button>`;document.body.append(d);d.querySelector('#plusAccountClose').onclick=()=>{d.close();d.remove()};d.querySelector('#plusLogout').onclick=async()=>{if(!confirm('이 기기에서 로그아웃할까요? 다시 사용하려면 기기 연결코드가 필요합니다.'))return;try{await request('/logout',{method:'POST'})}catch{}localStorage.removeItem(KEY);location.reload()};d.showModal()};
window.addEventListener('storage',e=>{if(e.key===KEY)check()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()});setInterval(()=>{if(pending&&!document.hidden)check()},15000);
show();check();
})();
