(()=>{'use strict';
const API='https://min-works-api.forjaejun.workers.dev';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=(offset=0)=>{const now=new Date(Date.now()+offset*86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)};
let selected=day(),busy=false,currentPhotos=[],photoIndex=0,lastFingerprint='',lastToday=day();
const money=n=>n===null||n===undefined||n===''?'미등록':Number(n)>=100000000?(Number(n)/100000000).toLocaleString('ko-KR',{maximumFractionDigits:2})+'억 원':Number(n)>=10000?(Number(n)/10000).toLocaleString('ko-KR',{maximumFractionDigits:1})+'만 원':Number(n).toLocaleString('ko-KR')+'원';
const safePhoto=src=>{try{const u=new URL(src,location.href);return /^data:image\/(png|jpeg|webp|gif);/i.test(src)||u.protocol==='https:'||u.origin===location.origin?src:''}catch{return''}};
function render(data){const rows=data.reports||[];$('#count').textContent=rows.length;$('#reports').innerHTML=rows.length?rows.map((r,i)=>{const photos=(r.photos||[]).filter(p=>safePhoto(p.src));const progress=Math.min(100,Math.max(0,Number(r.progress)||0));return `<article class="report"><div class="report-top"><h2>${esc(r.site)}</h2><time>${esc(r.time||'')}</time></div><p class="work">${esc((r.processes||[]).map(p=>p.work||p.name).filter(Boolean).join(' · ')||'작업내용 미등록')}</p><div class="numbers"><div><span>공사비</span><b title="${esc(r.amount)}원">${money(r.amount)}</b></div><div><span>추가 예상비</span><b>${money(r.extraAmount)}</b></div><div><span>공정률</span><b>${progress}%</b><div class="progress"><i style="width:${progress}%"></i></div></div></div><div class="photos">${photos.slice(0,3).map((p,j)=>`<button data-report="${i}" data-photo="${j}" aria-label="${esc(r.site)} 사진 ${j+1} 확대"><img src="${esc(safePhoto(p.src))}" loading="lazy" alt="현장사진 ${j+1}">${j===2&&photos.length>3?`<em>+${photos.length-2}</em>`:''}</button>`).join('')||'<small>등록된 사진 없음</small>'}</div><div class="meta"><span>${esc(r.author||'작성자 미등록')} · ${Number(r.totalPeople)||0}명</span><span>작업일 ${esc(r.reportDate||'—')}</span></div><details><summary>일보 내용 보기</summary>${(r.processes||[]).map(p=>`<div class="workline"><b>${esc(p.name)} · ${Number(p.today)||0}명</b><br>${esc(p.work)}</div>`).join('')}<p>${esc(r.note||'특이사항 없음')}</p></details></article>`}).join(''):'<div class="empty"><b>등록된 일보가 없습니다</b>날짜를 선택해 이전 일보를 확인하세요.</div>';
$('#reports').querySelectorAll('[data-photo]').forEach(b=>b.addEventListener('click',()=>{currentPhotos=(rows[Number(b.dataset.report)].photos||[]).filter(p=>safePhoto(p.src));photoIndex=Number(b.dataset.photo);showPhoto();$('#photoDialog').showModal()}));}
function showPhoto(){$('#largePhoto').src=safePhoto(currentPhotos[photoIndex]?.src||'');$('#photoCount').textContent=`${photoIndex+1} / ${currentPhotos.length}`;$('.photo-stage').classList.remove('zoomed');$('#zoomPhoto').textContent='확대 ＋';$('#prevPhoto').disabled=photoIndex===0;$('#nextPhoto').disabled=photoIndex===currentPhotos.length-1}
async function load(){if(busy)return;busy=true;$('#refresh').disabled=true;const requested=selected;try{const token=localStorage.getItem('minWorksSessionV1');if(!token){lastFingerprint='';$('#count').textContent='—';$('#photoDialog').close();$('#largePhoto').removeAttribute('src');currentPhotos=[];$('#reports').innerHTML='<div class="empty"><b>로그인이 필요합니다</b><a href="./index.html?reader=1">민웍스로 로그인</a></div>';$('#sync').textContent='로그인 대기';return}const response=await fetch(API+'/daily-reader?date='+encodeURIComponent(requested),{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!response.ok){const message=response.status===403?'관리자가 지정한 계정만 열람할 수 있습니다.':response.status===401?'로그인이 만료되었습니다. 민웍스에서 다시 로그인하세요.':'일보를 불러오지 못했습니다. 새로고침해 주세요.';if([401,403].includes(response.status)){lastFingerprint='';$('#reports').replaceChildren();$('#count').textContent='—';$('#photoDialog').close();$('#largePhoto').removeAttribute('src');currentPhotos=[]}throw Error(message)}const data=await response.json();if(selected!==requested)return;const fingerprint=JSON.stringify(data);if(fingerprint!==lastFingerprint){render(data);lastFingerprint=fingerprint}$('#notice').textContent='';$('#sync').textContent=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})+' 갱신';}catch(e){$('#notice').textContent=e.message;$('#sync').textContent='연결 확인 필요'}finally{busy=false;$('#refresh').disabled=false;if(selected!==requested)load()}}
function select(date){selected=date;$('#date').value=date;$('#today').classList.toggle('selected',date===day());$('#yesterday').classList.toggle('selected',date===day(-1));$('#summaryLabel').textContent=date===day()?'오늘 올라온 공사일보':date===day(-1)?'전일 올라온 공사일보':date+' 올라온 공사일보';lastFingerprint='';$('#reports').replaceChildren();$('#count').textContent='—';load()}
$('#today').onclick=()=>select(day());$('#yesterday').onclick=()=>select(day(-1));$('#date').onchange=()=>$('#date').value&&select($('#date').value);$('#refresh').onclick=load;$('#closePhoto').onclick=()=>$('#photoDialog').close();$('#prevPhoto').onclick=()=>{if(photoIndex>0){photoIndex--;showPhoto()}};$('#nextPhoto').onclick=()=>{if(photoIndex<currentPhotos.length-1){photoIndex++;showPhoto()}};$('#zoomPhoto').onclick=()=>{$('.photo-stage').classList.toggle('zoomed');$('#zoomPhoto').textContent=$('.photo-stage').classList.contains('zoomed')?'축소 −':'확대 ＋'};document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});window.addEventListener('storage',e=>{if(e.key==='minWorksSessionV1')load()});setInterval(()=>{if(document.hidden)return;const today=day();if(today!==lastToday){const wasToday=selected===lastToday;lastToday=today;if(wasToday)return select(today)}load()},15000);select(selected);
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
