(()=>{'use strict';
const API='https://min-works-api.forjaejun.workers.dev';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const day=(offset=0)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(Date.now()+offset*86400000));
let selected=day(),busy=false,currentPhotos=[],photoIndex=0,lastFingerprint='',lastToday=day(),groups=[],siteIndex=0,reportIndex=0,gesture=null,suppressClickUntil=0;
const money=n=>n===null||n===undefined||n===''?'미등록':Number(n)>=100000000?(Number(n)/100000000).toLocaleString('ko-KR',{maximumFractionDigits:2})+'억 원':Number(n)>=10000?(Number(n)/10000).toLocaleString('ko-KR',{maximumFractionDigits:1})+'만 원':Number(n).toLocaleString('ko-KR')+'원';
const safePhoto=src=>{try{const u=new URL(src,location.href);return /^data:image\/(png|jpeg|webp|gif);/i.test(src)||u.protocol==='https:'||u.origin===location.origin?src:''}catch{return''}};
const current=()=>groups[siteIndex]?.reports[reportIndex];
function pager(){$('#pagePosition').textContent=groups.length?`${siteIndex+1} / ${groups.length} 현장`:'0 / 0 현장';$('#prevSite').disabled=siteIndex<=0;$('#nextSite').disabled=siteIndex>=groups.length-1;$('#swipeHint').textContent=groups.length>1?'좌우로 넘겨 현장 보기':'조회 전용 · 15초마다 갱신'}
function closePhotos(){$('#photoDialog').close();$('#largePhoto').removeAttribute('src');currentPhotos=[]}
function clear(){groups=[];siteIndex=reportIndex=0;lastFingerprint='';$('#count').textContent='—';$('#reports').replaceChildren();closePhotos();$('#detailDialog').close();pager()}
function detail(){const r=current();if(!r)return;$('#detailContent').innerHTML=`<h2>${esc(r.site)}</h2><p>${esc(r.author||'작성자 미등록')} · ${Number(r.totalPeople)||0}명 · ${esc(r.reportDate)}</p>${(r.processes||[]).map(p=>`<div class="workline"><b>${esc(p.name)} · ${Number(p.today)||0}명</b><br>${esc(p.work)}</div>`).join('')}<h3>특이사항</h3><p>${esc(r.note||'특이사항 없음')}</p>`}
function draw(direction=0){const r=current();pager();if(!r){$('#reports').innerHTML='<div class="empty"><b>등록된 일보가 없습니다</b>날짜를 선택해 이전 일보를 확인하세요.</div>';return}const photos=(r.photos||[]).filter(p=>safePhoto(p.src)),progress=Math.min(100,Math.max(0,Number(r.progress)||0)),group=groups[siteIndex];
$('#reports').innerHTML=`<article class="report ${direction>0?'slide-next':direction<0?'slide-prev':''}" aria-label="${esc(r.site)} 공사일보"><div class="report-top"><h2>${esc(r.site)}</h2><time>${esc(r.time||'')}</time></div><p class="work">${esc((r.processes||[]).map(p=>p.work||p.name).filter(Boolean).join(' · ')||'작업내용 미등록')}</p><div class="numbers"><div><span>공사비</span><b title="${esc(r.amount)}원">${money(r.amount)}</b></div><div><span>추가 예상비</span><b>${money(r.extraAmount)}</b></div><div><span>공정률</span><b>${progress}%</b><div class="progress"><i style="width:${progress}%"></i></div></div></div><div class="photos">${photos.slice(0,3).map((p,j)=>`<button data-photo="${j}" aria-label="${esc(r.site)} 사진 ${j+1} 확대"><img draggable="false" src="${esc(safePhoto(p.src))}" alt="현장사진 ${j+1}">${j===2&&photos.length>3?`<em>+${photos.length-2}</em>`:''}</button>`).join('')||'<small>등록된 사진 없음</small>'}</div><div class="meta"><span>${esc(r.author||'작성자 미등록')} · ${Number(r.totalPeople)||0}명</span><span>작업일 ${esc(r.reportDate||'—')}</span></div><div class="report-bottom">${group.reports.length>1?`<select id="reportSelect" aria-label="이 현장의 일보 선택">${group.reports.map((x,i)=>`<option value="${i}" ${i===reportIndex?'selected':''}>${i+1}번째 일보 · ${esc(x.author||x.time||'작성자 미등록')}</option>`).join('')}</select>`:''}<button id="showDetail">일보 전체 보기 ↗</button></div></article>`;
$('#reportSelect')?.addEventListener('change',e=>{reportIndex=Number(e.target.value);closePhotos();draw()});$('#showDetail').onclick=()=>{detail();$('#detailDialog').showModal()};$('#reports').querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{currentPhotos=photos;photoIndex=Number(b.dataset.photo);showPhoto();$('#photoDialog').showModal()});
}
function render(data){const oldSite=groups[siteIndex]?.key,oldId=current()?.id,rows=data.reports||[],bySite=new Map;for(const r of rows){const key=r.site||'현장 미등록';if(!bySite.has(key))bySite.set(key,{key,reports:[]});bySite.get(key).reports.push(r)}groups=[...bySite.values()];siteIndex=Math.max(0,groups.findIndex(g=>g.key===oldSite));reportIndex=Math.max(0,groups[siteIndex]?.reports.findIndex(r=>r.id===oldId)??0);draw();if($('#detailDialog').open){if(current()?.id===oldId)detail();else $('#detailDialog').close()}if($('#photoDialog').open){if(current()?.id!==oldId)closePhotos();else{const src=currentPhotos[photoIndex]?.src;currentPhotos=(current().photos||[]).filter(p=>safePhoto(p.src));photoIndex=currentPhotos.findIndex(p=>p.src===src);if(photoIndex<0)closePhotos();else showPhoto()}}}
function move(delta){const next=siteIndex+delta;if(next<0||next>=groups.length)return;siteIndex=next;reportIndex=0;closePhotos();$('#detailDialog').close();draw(delta)}
function showPhoto(){$('#largePhoto').src=safePhoto(currentPhotos[photoIndex]?.src||'');$('#photoCount').textContent=`${photoIndex+1} / ${currentPhotos.length}`;$('.photo-stage').classList.remove('zoomed');$('#zoomPhoto').textContent='확대 ＋';$('#prevPhoto').disabled=photoIndex===0;$('#nextPhoto').disabled=photoIndex===currentPhotos.length-1}
async function load(){if(busy||!window.MINWORKS_PLUS_READY)return;busy=true;$('#refresh').disabled=true;const requested=selected;try{const token=localStorage.getItem('minWorksSessionV1');if(!token){clear();$('#reports').innerHTML='<div class="empty"><b>로그인이 필요합니다</b><a href="./index.html?reader=1">민웍스로 로그인</a></div>';$('#sync').textContent='로그인 대기';return}const response=await fetch(API+'/daily-reader?date='+encodeURIComponent(requested),{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(selected!==requested)return;if(!response.ok){if([401,403].includes(response.status)){clear();window.MINWORKS_PLUS_AUTH?.check();}throw Error(response.status===403?'관리자가 지정한 계정만 열람할 수 있습니다.':response.status===401?'로그인이 만료되었습니다. 민웍스에서 다시 로그인하세요.':'연결이 끊겼습니다. 마지막 조회 자료를 표시합니다.')}const data=await response.json();if(selected!==requested)return;let todayData=data;if(requested!==day()){const todayResponse=await fetch(API+'/daily-reader?date='+encodeURIComponent(day()),{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!todayResponse.ok)throw Error('오늘 등록 건수를 확인하지 못했어요. 새로고침해 주세요.');todayData=await todayResponse.json()}if(selected!==requested)return;$('#count').textContent='+'+(todayData.reports||[]).length;const fingerprint=JSON.stringify(data);if(fingerprint!==lastFingerprint){render(data);lastFingerprint=fingerprint}$('#notice').textContent='';$('#sync').textContent=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})+' 갱신';}catch(e){$('#notice').textContent=e.message;$('#sync').textContent='연결 확인 필요'}finally{busy=false;$('#refresh').disabled=false;if(selected!==requested)load()}}
function select(date){selected=date;$('#date').value=date;$('#today').classList.toggle('selected',date===day());$('#yesterday').classList.toggle('selected',date===day(-1));$('#summaryLabel').textContent=date===day()?'오늘 올라온 공사일보':date===day(-1)?'전일 올라온 공사일보':date+' 공사일보';clear();load()}
const surface=$('#reports');surface.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0||e.target.closest('select'))return;gesture={id:e.pointerId,x:e.clientX,y:e.clientY}});surface.addEventListener('pointerup',e=>{if(!gesture||e.pointerId!==gesture.id)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;gesture=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.4){suppressClickUntil=Date.now()+350;move(dx<0?1:-1)}});surface.addEventListener('pointercancel',()=>gesture=null);surface.addEventListener('pointerleave',()=>gesture=null);surface.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation()}},true);surface.addEventListener('dragstart',e=>e.preventDefault());surface.addEventListener('keydown',e=>{if(e.target.closest('select'))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1)}});
$('#prevSite').onclick=()=>move(-1);$('#nextSite').onclick=()=>move(1);$('#today').onclick=()=>select(day());$('#yesterday').onclick=()=>select(day(-1));$('#date').onchange=()=>$('#date').value&&select($('#date').value);$('#refresh').onclick=load;$('#closeDetail').onclick=()=>$('#detailDialog').close();$('#closePhoto').onclick=closePhotos;$('#prevPhoto').onclick=()=>{if(photoIndex>0){photoIndex--;showPhoto()}};$('#nextPhoto').onclick=()=>{if(photoIndex<currentPhotos.length-1){photoIndex++;showPhoto()}};$('#zoomPhoto').onclick=()=>{$('.photo-stage').classList.toggle('zoomed');$('#zoomPhoto').textContent=$('.photo-stage').classList.contains('zoomed')?'축소 −':'확대 ＋'};document.addEventListener('visibilitychange',()=>{if(!document.hidden)load()});window.addEventListener('storage',e=>{if(e.key==='minWorksSessionV1')load()});setInterval(()=>{if(document.hidden)return;const today=day();if(today!==lastToday){const wasToday=selected===lastToday;lastToday=today;if(wasToday)return select(today)}load()},15000);window.addEventListener('minworks:plus-ready',load);select(selected);
if('serviceWorker' in navigator&&!['localhost','127.0.0.1'].includes(location.hostname))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();

