let spots=[], user=null, radius=3;
const $=s=>document.querySelector(s), results=$('#results'), status=$('#status'), count=$('#count'), empty=$('#emptyData');
const rad=x=>x*Math.PI/180;
function km(a,b){const R=6371,dLat=rad(b.lat-a.lat),dLon=rad(b.lng-a.lng);const x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function parseCSV(t){const lines=t.trim().split(/\r?\n/);if(lines.length<2)return[];const sep=lines[0].includes('\t')?'\t':',';const h=lines[0].split(sep).map(x=>x.replace(/^"|"$/g,'').trim());const find=(keys)=>h.findIndex(v=>keys.some(k=>v.toLowerCase().includes(k)));const ni=find(['설치장소명','장소명','place','name']), ai=find(['소재지','도로명주소','주소','address']), lati=find(['위도','latitude','lat']), lngi=find(['경도','longitude','lng','lon']), si=find(['ssid','와이파이명']);return lines.slice(1).map(line=>{const c=line.match(/("[^"]*(?:""[^"]*)*"|[^,\t]*)(?:,|\t|$)/g)?.map(v=>v.replace(/[,\t]$/,'').replace(/^"|"$/g,'').replace(/""/g,'"'))||[];return{name:c[ni]||'무료 와이파이',address:c[ai]||'',lat:+c[lati],lng:+c[lngi],ssid:c[si]||''}}).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lng))}
async function load(){try{const r=await fetch('wifi.csv',{cache:'no-store'});if(!r.ok)throw 0;spots=parseCSV(await r.text());status.textContent=`전국 와이파이 ${spots.length.toLocaleString()}곳 로드 완료`;render()}catch(e){status.textContent='전국 데이터 파일 연결 대기 중';empty.classList.remove('hidden')}}
function nav(place){return `https://map.naver.com/p/search/${encodeURIComponent(place.address||place.name)}`}
function render(list=spots){let a=[...list];if(user)a=a.map(x=>({...x,d:km(user,x)})).filter(x=>x.d<=radius).sort((x,y)=>x.d-y.d);const q=$('#query').value.trim().toLowerCase();if(q)a=a.filter(x=>(x.name+' '+x.address+' '+x.ssid).toLowerCase().includes(q));a=a.slice(0,100);count.textContent=`${a.length.toLocaleString()}곳`;results.innerHTML=a.map(x=>`<article class="place"><div class="place-top"><div><h3>📡 ${x.name}</h3><p>${x.address}</p>${x.ssid?`<p>Wi‑Fi: ${x.ssid}</p>`:''}</div>${x.d!=null?`<span class="distance">${x.d<1?Math.round(x.d*1000)+'m':x.d.toFixed(1)+'km'}</span>`:''}</div><div class="actions"><a href="${nav(x)}" target="_blank">네이버지도</a><a href="https://map.kakao.com/link/search/${encodeURIComponent(x.address||x.name)}" target="_blank">카카오맵</a></div></article>`).join('')||'<div class="empty"><b>조건에 맞는 장소가 없어.</b><p>검색 반경을 넓혀봐.</p></div>'}
$('#nearBtn').onclick=()=>{status.textContent='현재 위치 확인 중…';navigator.geolocation.getCurrentPosition(p=>{user={lat:p.coords.latitude,lng:p.coords.longitude};status.textContent=`내 위치 기준 ${radius}km 검색`;render()},()=>status.textContent='위치 권한을 허용해줘 📍',{enableHighAccuracy:true,timeout:10000})};
$('#searchBtn').onclick=()=>render();$('#query').addEventListener('input',()=>render());document.querySelectorAll('[data-radius]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-radius]').forEach(x=>x.classList.remove('active'));b.classList.add('active');radius=+b.dataset.radius;if(user){status.textContent=`내 위치 기준 ${radius}km 검색`;render()}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load();